[package]
name = "wkd_load"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bytes = "1.10.0"
miette = "7.5.0"
sequoia-openpgp = { version = "1.22.0", default-features = false, features = ["crypto-openssl"] }
thiserror = "2.0.11"
