[package]
name = "wkd-tester"
version = "0.1.0"
edition = "2021"
license = "MIT"
author = ["Alexis Lowe <alexis.lowe@chimbosonic.com>"]
description = "A CLI tool for testing and debugging OpenPGP Web Key Directory (WKD)"
keywords = ["cli", "wkd", "OpenPGP"]

[[bin]]
name = "wkd-tester"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
miette = { version = "7.5.0", features = ["fancy"] }
wkd_uri = { path = "../wkd_uri" }

