[package]
name = "wkd_fetch"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.10.0"
miette = "7.5.0"
reqwest = "0.12.12"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
url = "2.5.4"
wkd_uri = { path = "../wkd_uri" }

[dev-dependencies]
mockito = "1.6.1"
